name: BSN Frontend Pipeline

on:
  push:
    branches:
      - ci/pipeline
    paths:
      - book-network-ui/**
      - docker/frontend/**
      - 'docker-compose.yml'
      - .github/workflows/*-frontend.yml
jobs:
  build-image:
    name: Build FE Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Extract project version
        id: extract_version
        run: |
          cd book-network-ui
          echo "VERSION=$(jq -r '.version' package.json)" >> $GITHUB_OUTPUT

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push to DockerHub
        uses: docker/build-push-action@v5
        with:
          context: book-network-ui
          file: docker/frontend/Dockerfile
          push: true
          platforms: linux/amd64
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/bsn-ui:latest,${{ secrets.DOCKERHUB_USERNAME }}/bsn-ui:${{ steps.extract_version.outputs.VERSION }}

  deploy:
    name: Deploy Frontend
    runs-on: ubuntu-latest
    needs: [ build-image ]
    steps:
      - name: Set up SSH key
        run: |
          echo "${{ secrets.AWS_SSH_PRIVATE_KEY }}" > aws_key.pem
          chmod 400 aws_key.pem
        
      - name: Create deployment folder
        run: |
          ssh -o StrictHostKeyChecking=no \
              -o UserKnownHostsFile=/dev/null \
              -o LogLevel=ERROR \
              -i aws_key.pem \
              ubuntu@ec2-54-88-192-148.compute-1.amazonaws.com \
              "mkdir -p ci-cd"

      - name: Copy docker-compose file
        run: |
          scp -o StrictHostKeyChecking=no \
              -o UserKnownHostsFile=/dev/null \
              -o LogLevel=ERROR \
              -i aws_key.pem \
              docker-compose.yml \
              ubuntu@ec2-54-88-192-148.compute-1.amazonaws.com:ci-cd/

      - name: Deploy application
        run: |
          ssh -o StrictHostKeyChecking=no \
              -o UserKnownHostsFile=/dev/null \
              -o LogLevel=ERROR \
              -i aws_key.pem \
              ubuntu@ec2-54-88-192-148.compute-1.amazonaws.com << 'EOF'
          set -e
          export IMAGE_TAG=${{ steps.extract_version.outputs.VERSION }}
          cd ci-cd
          docker compose -f docker-compose.yml pull
          docker compose -f docker-compose.yml up -d
          docker ps --filter "name=bsn-ui" --format "{{.Status}}" | grep -q "Up"
          echo "Deployment successful"
          EOF
#  health-check:
#    name: UI Health Check
#    runs-on: ubuntu-latest
#    needs: [deploy]
#    steps:
#      - name: Check the docker container health status
#        run: |
#          if ! docker ps -a | grep bsn-ui; then
#            echo "Container is not running"
#            exit 1
#          fi
